# Generated by Django 4.2.7 on 2023-11-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
    ]
